#   Copyright (C) 2024 John Törnblom
#
# This file is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING. If not see
# <http://www.gnu.org/licenses/>.

ifdef PS5_PAYLOAD_SDK
    include $(PS5_PAYLOAD_SDK)/toolchain/prospero.mk
else
    $(error PS5_PAYLOAD_SDK is undefined)
endif

CFLAGS := -O3 -I ./snes -I ./zip \
          `${PS5_PAYLOAD_SDK}/bin/prospero-sdl2-config --cflags --libs` \
	  -lkernel_sys -lSDL2main -lSceSystemService

SRCS := snes/spc.c snes/dsp.c snes/apu.c snes/cpu.c snes/dma.c snes/ppu.c \
        snes/cart.c snes/cx4.c snes/input.c snes/statehandler.c snes/snes.c \
        snes/snes_other.c zip/zip.c tracing.c main.c

HDRS := snes/spc.h snes/dsp.h snes/apu.h snes/cpu.h snes/dma.h snes/ppu.h \
        snes/cart.h snes/cx4.h snes/input.h snes/statehandler.h snes/snes.h \
        zip/zip.h zip/miniz.h tracing.h

all: lakesnes

lakesnes: $(SRCS) $(HDRS)
	$(CC) $(CFLAGS) -o $@ $(SRCS)

clean:
	rm -f lakesnes

install: lakesnes homebrew.js sce_sys/icon0.png
	install -Dm 644 sce_sys/icon0.png -t "${DESTDIR}/${PREFIX}/LakeSnes/sce_sys"
	install -Dm 644 homebrew.js -t "${DESTDIR}/${PREFIX}/LakeSnes"
	install -m 755 lakesnes -T "${DESTDIR}/${PREFIX}/LakeSnes/lakesnes.elf"
	install -m 755 -d "${DESTDIR}/${PREFIX}/LakeSnes/roms"
